# Generated by Django 3.2.23 on 2024-02-12 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20240129_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_wishlist',
            field=models.ManyToManyField(blank=True, related_name='is_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
