# Generated by Django 3.2.23 on 2024-02-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_wishlist',
        ),
    ]
